app/cast/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Length, EqualTo
from datetime import datetime

class PickForm(Form):
	artist = StringField('Artist', validators=[Required()])
	album = StringField('Album', validators=[Required()])
	song = StringField('Song', validators=[Required()])
	description = TextAreaField('Description')
	links = TextAreaField('Download Links (Separate with commas if more than one)')
	picture_url = StringField('Picture URL (optional)')
	submit = SubmitField('Submit!')

	def from_model(self, pick):
		self.artist.data = pick.artist
		self.album.data = pick.album
		self.song.data = pick.song
		self.description.data = pick.description
		self.links.data = pick.links
		self.picture_url.data = pick.picture_url

	def to_model(self, pick):
		pick.artist = self.artist.data
		pick.album = self.album.data
		pick.song = self.song.data
		pick.description = self.description.data
		pick.links = self.links.data
		pick.picture_url = self.picture_url.data

class CastForm(Form):
	cast_number = StringField('Cast Number', validators=[Required()])
	time = StringField('Time', validators=[Required()])
	date = StringField('Date', validators=[Required()])
	host = SelectField('Host', coerce=int, validators=[Required()])
	description = TextAreaField('Description')
	picture_url = StringField('Picture URL (optional)')
	submit = SubmitField('Submit')

	def from_model(self, cast):
		self.time.data = cast.time
		self.date.data = cast.date
		self.description.data = cast.description
		self.picture_url.data = cast.picture_url

	def to_model(self, cast):
		cast.time = self.time.data
		cast.date = self.date.data
		cast.description = self.description.data
		cast.picture_url = self.picture_url.data

class SearchForm(Form):
    search = StringField('Search')
    submit = SubmitField('Submit!')

class DeleteCastForm(Form):
	cast_number = PasswordField('Cast Number', [Required(), Length(1, 128), EqualTo('confirm', message='Numbers must match.')])
	confirm = PasswordField('Repeat Number')
	submit = SubmitField('Delete forever!')

app/cast/__init__.py
from flask import Blueprint
cast = Blueprint('cast', __name__)
from . import routes

app/cast/routes.py
from flask import render_template, redirect, url_for, flash, g, request
from flask.ext.login import login_required, current_user

from app.extensions import db
from . import cast
from .forms import PickForm, CastForm, SearchForm, DeleteCastForm
from .decorators import admin_required
from ..models import User, Cast, Pick

from datetime import datetime

@cast.route('/', endpoint='index')
@cast.route('/cast/', endpoint='view_next_cast')
@cast.route('/cast/<int:cast_number>', endpoint='view_cast')
@cast.route('/cast/<string:view_all>', endpoint='view_all_casts')
def index(cast_number=None, view_all=None):
	if cast_number:
		cast = Cast.query.filter_by(cast_number=int(cast_number)).first_or_404()
		return render_template('cast/cast.html', cast=cast)
	elif view_all == 'all':
		casts = Cast.query.all()
		return render_template('cast/view_all.html', casts=casts)

	cast = Cast.query.order_by(Cast.cast_number.desc()).first()
	return render_template('cast/index.html', cast=cast)

@cast.route('/pick/', methods=['GET', 'POST'])
@login_required
def pick():
	form = PickForm()
	if form.validate_on_submit():
		pick = Pick()

		form.to_model(pick)
		pick.cast = g.next_cast
		pick.author = current_user
		pick.date_added = datetime.utcnow()
		if g.next_cast.picks.count() > 0:
			last_position = Pick.query.filter_by(cast_id=g.next_cast.id).order_by(Pick.dj_list_position.desc()).first()
			if last_position.dj_list_position:
				pick.dj_list_position = last_position.dj_list_position+1 
			else:
				pick.dj_list_position = -1
		else:
			pick.dj_list_position = 0

		db.session.add(pick)
		db.session.commit()

		flash('Pick added successfully!')
		return redirect(url_for('cast.index'))

	return render_template('cast/pick.html', form=form)

@cast.route('/pick/<int:id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_pick(id=None):
	if not id:
		return redirect(url_for('cast.index'))

	pick = Pick.query.get(int(id))
	if not pick:
		flash('Invalid pick.')
		return redirect(url_for('cast.index'))
	if current_user.is_admin or pick.author.id == current_user.id:
		form = PickForm()
		if form.validate_on_submit():
			form.to_model(pick)
			pick.last_edited = datetime.utcnow()
			try:
				db.session.add(pick)
				db.session.commit()
			except:
				db.session.rollback()
				flash('Unknown error adding pick')
				return redirect(url_for('cast.index'))
			flash('Pick edited successfully.')
			return redirect(url_for('cast.index'))
		form.from_model(pick)
		return render_template('cast/edit_pick.html', form=form, pick=pick)
	else:
		flash('Invalid permissions.')
		return redirect(url_for('cast.index'))
	return redirect(url_for('cast.index'))

@cast.route('/pick/<int:id>/delete/', methods=['GET', 'POST'])
@login_required
def delete_pick(id=None):
	if not id:
		return redirect(url_for('cast.index'))

	pick = Pick.query.get(int(id))
	if not pick:
		flash('Invalid pick.')
		return redirect(url_for('cast.index'))
	if current_user.is_admin or pick.author.id == current_user.id:
		try:
			db.session.delete(pick)
			db.session.commit()
		except:
			flash('Couldn\'t delete pick')
		flash('Pick deleted')
	return redirect(url_for('cast.index'))	

@cast.route('/create/', methods=['GET', 'POST'])
@login_required
@admin_required
def create_cast():
	form = CastForm()
	form.host.choices = [ (user.id, user.username) for user in User.query.all()]

	if form.validate_on_submit():
		cast = Cast()
		form.to_model(cast)
		cast.host = User.query.get(form.host.data)
		cast.cast_number = form.cast_number.data

		db.session.add(cast)
		db.session.commit()

		flash('Cast added.')
		return redirect(url_for('cast.view_cast', cast_number=cast.cast_number))
	else:
		form.cast_number.data = g.next_cast.cast_number + 1  if g.next_cast else 1

	return render_template('cast/create.html', form=form)

@cast.route('/cast/<int:id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_cast(id=None):
	if not id:
		return redirect(url_for('cast.index'))

	cast = Cast.query.get(int(id))
	if not cast:
		flash('Invalid cast')
		return redirect(url_for('cast.index'))

	if current_user.is_admin or cast.host.id == current_user.id:
		form = CastForm()
		form.host.choices = [ (user.id, user.username) for user in User.query.all()]
		form.host.choices.insert(0, (cast.host.id, cast.host.username))

		del form.cast_number
		if form.validate_on_submit():
			form.to_model(cast)
			cast.host = User.query.get(form.host.data)
			try:
				db.session.add(cast)
				db.session.commit()
			except:
				flash('Unknown error editing cast!')
				return redirect(url_for('cast.index'))
			flash('Cast edited')
			return redirect(url_for('cast.view_cast', cast_number=cast.cast_number))
		form.from_model(cast)
		return render_template('/cast/edit_cast.html', form=form, cast=cast)
	else:
		flash('Invalid permissions')
		return redirect(url_for('cast.index'))
	return redirect(url_for('cast.index'))

@cast.route('/cast/<int:id>/delete/', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_cast(id=None):
	if not id:
		return redirect(url_for('cast.index'))
	cast = Cast.query.get(id)
	if not cast:
		flash('Invalid cast.')
		return redirect(url_for('cast.index'))

	form = DeleteCastForm()

	if form.validate_on_submit():
		if current_user.is_admin and int(form.confirm.data) == int(cast.cast_number):		
			for pick in cast.picks:
				db.session.delete(pick)
			db.session.delete(cast)
			try:
				db.session.commit()
			except Exception as e:
				print(e)
			flash('Cast deleted')
			return redirect(url_for('cast.index'))
		else:
			flash('Wrong cast number')

	return render_template('cast/delete.html', form=form, cast=cast)

@cast.route('/user/<string:username>', endpoint='user', methods=['GET', 'POST'])
def profile(username=None):
	user = User.query.filter_by(username=username).first_or_404()
	return render_template('cast/user.html', user=user)

@cast.route('/search/', endpoint='search_redirect', methods=['GET', 'POST'])
@cast.route('/search/<string:query>', endpoint='search')
def search(query=None):
	search_form = SearchForm(request.form)
	if search_form.search.data:
		return redirect(url_for('cast.search', query=search_form.search.data))

	results = None
	if query:
		results = Pick.query.whoosh_search(query).all()
	return render_template('cast/search.html', results=results)

app/templates/cast/_macros.html

{% macro build_pick(pick, moment, current_user) %}
<li class="list-group-item">

	<div class="media">
		<a class="thumbnail pull-left" href="#">
			<img src="{{ pick.picture_url if pick.picture_url else 'http://bongcast.com/static/img/unknown-album.png' }}" class="media-object" style="max-width: 200px;"/>
		</a>

		<div class="media-body" style="overflow: visible; display: inline;">
			<h3 class="media-heading">{{ pick.song }} <small>by</small> {{ pick.artist }} <small>on</small> {{ pick.album }}
    		</h3>
    		<span style="display: inline-block;">
    		<small> Picked by </small><a href="{{ url_for('cast.user', username=pick.author.username) }}">{{ pick.author.username }}</a> <small>on {{ moment(pick.date_added).format('MMMM Do, h:mm:ss a') }}.</small>
    		<span>&nbsp;</span>
    		</span>
    		{% if pick.links %}
    		<div class="dropdown" style="display: inline-block;">
	    		<button type="button" class="btn btn-default" data-toggle="dropdown">
					<span class="glyphicon glyphicon-arrow-down"></span> Download Links
				</button>

				<ul class="dropdown-menu" role="menu">
				{% for link in pick.links.split(',') %}
					<li><a href="{{ link }}" target="_blank">{{ link }}</a></li>
				{% endfor %}
				</ul>
			</div>
			{% endif %}
			{% if current_user.id == pick.author.id or current_user.is_admin %}
				<a class="btn btn-default" href="{{ url_for('cast.edit_pick', id=pick.id) }}">edit</a>
				<a class="btn btn-default" href="{{ url_for('cast.delete_pick', id=pick.id) }}">delete</a>
    		{% endif %}
    		<dd style="padding-top: 15px;">{{ pick.description | nl2br | safe }}</dd>
  		</div>
	</div>

	</li>
{% endmacro %}

{% macro build_cast_header(cast, current_user, list=False) %}
{% if cast and not list %}
<div class="jumbotron">
	<h2><strong>
		Cast <a href="{{ url_for('cast.view_cast', cast_number=cast.cast_number) }}">{{ cast.cast_number }}</a>
		</strong>

		<a href="{{ url_for('dj.index') }}#/{{ cast.cast_number }}" class="btn btn-primary" role="buttone">DJ</a> 
		{% if cast.id == g.next_cast.id %}
		<a href="{{ url_for('cast.pick') }}" class="btn btn-primary" role="button">Pick</a> 
		{% endif %}
		{% if current_user.is_admin or current_user.id == cast.host.id %}
			<a href="{{ url_for('cast.edit_cast', id=cast.id) }}" class="btn btn-primary" role="button">Edit</a>
		{% endif %}
		{% if current_user.is_admin %}
			<a href="{{ url_for('cast.delete_cast', id=cast.id) }}" class="btn btn-primary" role="button">Delete</a>
		{% endif %}
	</h2>

	<h2><p style="margin-left: 60px; font-size: 12pt;">
		hosted by 
		<a href="{{ url_for('cast.user', username=cast.host.username) }}">{{ cast.host.username }}</a> 
		<strong>on</strong> {{ cast.date }} 
		<strong>at</strong> {{ cast.time }} 
		<strong>with</strong> {{ cast.picks.count() }} picks
		</p>
	</h2>

	<div class="media">
		<a href="#" class="thumbnail pull-left">
			<img src="{{ cast.picture_url if cast.picture_url else '/static/img/unknown-album.png' }}" 
				style="max-width: 200px;" />
		</a>
		<p>{{ cast.description }}</p>
	</div>
</div>
{% endif %}
{% if cast and list %}
  <a href="{{ url_for('cast.view_cast', cast_number=cast.cast_number) }}" class="list-group-item">
    <h4 class="list-group-item-heading">Cast {{ cast.cast_number }} <small>hosted by</small> {{ cast.host.username }} <small>on</small> {{ cast.date }}</h4>
    <p class="list-group-item-text">{{ cast.description }}</p>
  </a>
{%endif %}
{% endmacro %}

app/templates/cast/cast.html
{% extends "base.html" %}

{% block page_content %}

{% from "cast/_macros.html" import build_cast_header, build_pick %}

{{ build_cast_header(cast, current_user=current_user) }}

{% for pick in cast.picks|sort(attribute='dj_list_position', reverse=False) %}
	{{ build_pick(pick, moment=moment, current_user=current_user) }}
{% endfor %}

{% endblock %}

app/templates/cast/create.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h2 class="page-header">Create the next cast! <small>Cast number auto-fills based on last cast</small></h2>
<div style="width: 50%">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cast/delete.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<h1 class="page-header">Are you sure you want to delete this cast (#{{ cast.cast_number }}) forever?<br />
<small>Type the cast number twice to confirm.</small></h1>
<div style="width: 50%">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cast/edit_cast.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h2 class="page-header">Editing cast <a href="{{ url_for('cast.view_cast', cast_number=cast.cast_number) }}">{{ cast.cast_number }}</a></h2>
<div style="width: 50%">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cast/edit_pick.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h2 class="page-header">Editing 
	<a href="{{ url_for('cast.user', username=pick.author.username) }}">{{ pick.author.username }}</a>'s pick on cast 
	<a href="{{ url_for('cast.view_cast', cast_number=pick.cast.cast_number) }}">{{ pick.cast.cast_number }}</a>
</h2>
<div style="width: 50%">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cast/index.html
{% extends "base.html" %}

{% block page_content %}

{% from "cast/_macros.html" import build_cast_header, build_pick %}

{{ build_cast_header(g.next_cast, current_user=current_user) }}

{% for pick in g.next_cast.picks|sort(attribute='dj_list_position', reverse=False) %}
	{{ build_pick(pick, moment=moment, current_user=current_user) }}
{% endfor %}

{% endblock %}

app/templates/cast/pick.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div style="width: 80%">
	<h2><small>
	    <dl>
	        <dt>The Four Pick Commandments </dt>
	        <dd><strong>1.</strong> Pick something interesting and unique.</dd>
	        <dd><strong>2.</strong> Consider the rest of the playlist during your pick. Will your pick add or detract from the variety of the playlist?</dd>
	        <dd><strong>3.</strong> Select a song less than five or six minutes in length, a radio-friendly duration.</dd>
	        <dd><strong>4.</strong> Try and keep it fresh by choosing a song you added to your library within the last month.</dd>
	    </dl>
	</small></h2>
</div>
<div style="width: 50%">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cast/search.html
{% extends "base.html" %}

{% block page_content %}
{% if results %}
{% from "cast/_macros.html" import build_pick %}
<h2 class="page-header">{{ results | count }} {{ 'result' if (results | count == 1) else 'results' }}</h2>
{% for pick in results %}
	<h3><small>On cast {{ pick.cast.cast_number }}</small></h3>
	{{ build_pick(pick, moment, current_user) }}
{% endfor %}

{% else %}
<h2 class="page-header">No results found.</h2>
{% endif %}
{% endblock %}

app/templates/cast/user.html
{% extends "base.html" %}

{% block page_content %}
<div class=" row page-header">
	<img class="img-rounded pull-left" style="margin-right: 10px; max-height: 200px;" src="{{ user.avatar_url if user.avatar_url else '/static/img/default_avatar.jpg' }}" />
	<h1>
	{{ user.username }}
	</h1>
	{% if current_user.is_admin %}
	<a href="{{ url_for('auth.edit_user', username=user.username) }}" class="btn btn-default">Edit user</a>
	{% elif current_user.id == user.id %}
	<a href="{{ url_for('auth.settings') }}" class="btn btn-default">Settings</a>
	{% endif %}
</div>

{% from "cast/_macros.html" import build_pick %}
<ul class="list-group">
	<h3>Picks ({{ user.picks.count() }} total)</h3>
	{% for pick in user.picks|sort(attribute='id', reverse=True) %}
		<h3 class="page-header"><small>On cast {{ pick.cast.cast_number }}</small></h3>
		{{ build_pick(pick, moment, current_user) }}
	{% endfor %}
</ul>
{% endblock %}

app/templates/cast/view_all.html
{% extends "base.html" %}

{% block page_content %}

{% from "cast/_macros.html" import build_cast_header %}
<div class="list-group">
{% for cast in casts|sort(attribute='cast_number', reverse=True) %}
	{{ build_cast_header(cast, current_user=current_user, list=True) }}
{% endfor %}
</div>
{% endblock %}