app/api_1_0/__init__.py
from flask import Blueprint, render_template
api = Blueprint('api', __name__)
from . import casts, picks, users, links, errors

@api.route('/')
def index():
	return render_template('api_1_0/index.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block metas %}<meta name="viewport" content="width=device-width, initial-scale=1.0">{% endblock %}
{% block title %}Cast{% endblock %}

{% block content %}
<nav class="navbar navbar-inverse" role="navigation">

<div class="container-fluid" style="width: 70%">
	<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('cast.index') }}">#420@P2PNET</a>
    </div>

    <ul class="nav navbar-nav">
		<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cast <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="{{ url_for('cast.pick') }}">Pick!</a></li>
	            <li><a href="{{ url_for('cast.view_next_cast') }}">View Next Cast</a></li>
	            <li><a href="{{ url_for('cast.view_all_casts', view_all='all') }}">Previous Casts</a></li>
	            <li><a href="{{ url_for('api.index') }}">API endpoints</a></li>
	            {% if current_user.is_admin %}
	            <li class="divider"></li>
	            <li><a href="{{ url_for('cast.create_cast') }}">Create Cast</a></li>
	            {% endif %}
	          </ul>
	    </li>
	</ul>
	<form class="navbar-form navbar-left" role="search" method="post" action="{{ url_for('cast.search_redirect') }}">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Search" name="search">
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
	{% if current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
		<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.username }} <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="{{ url_for('cast.user', username=current_user.username) }}">Profile</a></li>
	            <li><a href="{{ url_for('auth.settings') }}">Settings</a></li>
	            <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
	            {% if current_user.is_admin %}
	            <li class="divider"></li>
	            <li><a href="{{ url_for('admin.index') }}">Admin Panel</a></li>
	            {% endif %}
	          </ul>
	    </li>
	</ul>
	{% else %}
	<form method="post" class="navbar-form navbar-right" action="#">
		<div class="form-group">
			<a href="{{ url_for('auth.login') }}" class="btn btn-default" role="button">Log in</a>
			<a href="{{ url_for('auth.register') }}" class="btn btn-default" role="button">Register</a></li>
		</div>
	</form>
	{% endif %}
</div>

</nav>

{% for category, message in get_flashed_messages(with_categories=true) %}
<div class="alert alert-warning">
	{{ message }}
	{% if category[-12:] == 'announcement' and current_user.is_admin %}
	<a href="{{ url_for('admin.delete_announcement', id=category[:-12]) }}" class="btn btn-default pull-right">Delete</a>
	{% endif %}
</div>
{% endfor %}

<div class="container">
	{% block page_content %}{% endblock %}
</div>
<footer style="text-align: center;">
	<p>_\|/_</p>
</footer>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
{{ moment.include_jquery() }}
{{ moment.include_moment() }}
<script src="../../static/js/settings.js"></script>
{% endblock %}